version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7 
    steps:
      - checkout  
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run pytest
          command: |
            pytest test_Recipe_Management_System.py
            pytest test_exception_Recipe_Management_System.py
