version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7 
    working_directory: /home/circleci/project
    steps:
      - checkout  
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run pytest
          command: |
            pytest /home/circleci/project/test_Recipe_Management_System
            pytest /home/circleci/project/test_exception_Recipe_Management_System
