version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout

      
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      
      - run:
          name: Run tests with coverage
          command: |
            . venv/bin/activate
            pytest -s -v --cov=RecipeManagementSystem
